/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp qmltuner.xml -a qmldbusadaptor.h:qmldbusadaptor.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QMLDBUSADAPTOR_H_1374683654
#define QMLDBUSADAPTOR_H_1374683654

#include <QtDBus/QtDBus>
#include <QtCore/QVector>

#include "qmltunertypes.h"

/*
 * Adaptor class for interface com.luxoft.qmltuner
 */
class QmlTunerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.luxoft.qmltuner")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.luxoft.qmltuner\">\n"
"    <method name=\"enumerateItems\">\n"
"      <arg direction=\"out\" type=\"a(sssa{ss})\" name=\"items\"/>\n"
"    </method>\n"
"    <method name=\"describeItem\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"address\"/>\n"
"      <arg direction=\"out\" type=\"(sssa{ss})\" name=\"properties\"/>\n"
"    </method>\n"
"    <method name=\"setProperty\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"itemAddress\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"property\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"    <method name=\"highlight\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"itemAddress\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"    <method name=\"showTarget\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"pathToFile\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"opacity\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QmlTunerAdaptor(QObject *parent);
    virtual ~QmlTunerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    virtual ItemNotation describeItem(const QString &address) = 0;
    virtual QVector<ItemNotation> enumerateItems() = 0;
    virtual bool setProperty(const QString &itemAddress, const QString &property, const QString &value) = 0;
    virtual bool highlight(const QString &itemAddress) = 0;
    virtual bool showTarget(const QString &pathToFile, double opacity) = 0;
Q_SIGNALS: // SIGNALS
};

#endif
